### ISSUE TITLE
optimize SerializedPacket copy/move

### ISSUE THREAD

**Issue by ktprime** [google/quiche#35]
in file quic_packet_creator.h 
change 
`virtual void OnSerializedPacket(SerializedPacket serialized_packet) = 0
`to 
`virtual void OnSerializedPacket(SerializedPacket& serialized_packet) = 0
`
can reduce twice copy/move SerializedPacket.

in file quic_packet_creator.cc 
```
  SerializedPacket packet(std::move(packet_));
  ClearPacket();
  RemoveSoftMaxPacketLength();
  delegate_->OnSerializedPacket(packet); //no need more/copy now,

```
some other interface also need changed (use reference to replace move )

**Comment by bencebeky** [comment]
Moves are cheap.  The second move in `QuicPacketCreator::OnSerializedPacket()` is likely to be optimized away by the compiler.  On the other hand, if `QuicPacketCreator::DelegateInterface::OnSerializedPacket()` was changed to take `SerializedPacket` by reference instead of value, then the `SerializedPacket` object would need to be copied in the last line of `QuicConnection::OnSerializedPacket()`:

```
SendOrQueuePacket(std::move(serialized_packet));
```

So the proposed change would unfortunately increase the number of copies.

**Comment by ktprime** [comment]
no any copy increased by my ideal.  I have used this in my projecet, from linux perf
benchmark it can reduce tiny cpu. some the other interface also adjust. 

for example

```
void QuicConnection::SendOrQueuePacket(SerializedPacket& packet) {
  // The caller of this function is responsible for checking CanWrite().
  WritePacket(&packet);
}
```

//test on vs2022
![image](https://user-images.githubusercontent.com/1461362/215630453-b444a0be-3fdb-4c77-bcb3-b143495dbe18.png)
