### ISSUE TITLE
The transport parameters obtained from ParseTransportParameters(...) differ from those initially serialized.

### ISSUE THREAD

**Issue by kinokrt** [google/quiche#65]
When I serialize transport parameters with `quic::SerializeTransportParameters(...)` and then deserialize with `quic::ParseTransportParameters(...)` I don't get the same.

I see there:
```
// Removes reserved values from custom_parameters and versions.                                                                                
// The resulting value can be reliably compared with an original or other                                                                      
// deserialized value.                                                                                                                         
QUICHE_EXPORT void DegreaseTransportParameters(TransportParameters& parameters); 
```

So it's expected to call `DegreaseTransportParameters(...)` before the comparison.

Anyway, the usual expectation is to get exactly the same thing that was serialized during deserialization. Any additional changes required should not be part of the deserialization process itself.

**Comment by DavidSchinazi** [comment]
This is intentional. QUIC leverages [GREASE](https://www.rfc-editor.org/rfc/rfc8701.html) to ensure that all implementations handle unknown extensions properly. In practice, transport parameters should never be compared - the only use of received parameters is to check known values. The only place where comparisons make sense is tests, and that's why we have `DegreaseTransportParameters()`.

**Comment by kinokrt** [comment]
Thank you for your answer. However, I still believe that serialization and deserialization should maintain symmetry. What is serialized should exactly match what is deserialized. In my opinion, applying randomization afterward might be a better approach.

**Comment by kinokrt** [comment]
OK, no problem. Thank you.
